# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reliquary < Formula
  desc "Your digital asset guardian."
  homepage "https://github.com/SentimentalK/Reliquary"
  version "0.7.1"
  license "Private"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/SentimentalK/Reliquary/releases/download/v0.7.1/reliquary_Darwin_x86_64.tar.gz"
    sha256 "942361e70c8b10bee3087ec650df6d50059e23481d187a86753363525146bacd"

    def install
      bin.install "reliquary"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/SentimentalK/Reliquary/releases/download/v0.7.1/reliquary_Darwin_arm64.tar.gz"
    sha256 "67ae06d0e4beadc2af4c331e8125af39d8882321944b1a76532a5e989624c1cd"

    def install
      bin.install "reliquary"
    end
  end
end
